name: Gitea
version: "1.1.4"
slug: gitea
description: Private Git service for hobby projects
arch:
  - amd64
  - aarch64
url: "https://gitea.io"
startup: system
init: false
map:
  - share:rw
options:
  hostname: "gitea.local"
  http_port: "3000"
  ssh_port: 2222
  root_url: null
schema:
  hostname: "str?"
  http_port: "int?"
  ssh_port: "int?"
  root_url: "str?"
env:
  - GITEA_ADMIN_PASSWORD
  - GITEA_SSH_PORT
  - GITEA_ROOT_URL
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "HTTP"
image: "ghcr.io/flozsc/{arch}-addon-gitea"
