name: Gitea
version: "1.0.4"
slug: gitea
description: Private Git service for hobby projects
arch:
  - amd64
  - aarch64
url: "https://gitea.io"
startup: system
init: false
map:
  - share:rw
options:
  hostname: "gitea.local"
  http_port: "3000"
  ssh_port: 2222
schema:
  hostname: "str?"
  http_port: "int?"
  ssh_port: "int?"
env:
  - GITEA_ADMIN_PASSWORD
  - GITEA_SSH_PORT
image: "ghcr.io/flozsc/{arch}-addon-gitea"
