#!/bin/sh
set -e

if [ -n "$GITEA_ADMIN_PASSWORD" ]; then
    export GITEA_ADMIN_PASSWORD
fi

CONFIG_FILE="/data/gitea/conf/app.ini"

if [ -f "$CONFIG_FILE" ]; then
    if [ -n "$GITEA_SSH_PORT" ]; then
        if [ "$GITEA_SSH_PORT" = "0" ]; then
            sed -i "s/^SSH_PORT = .*/SSH_PORT = -1/" "$CONFIG_FILE"
        else
            sed -i "s/^SSH_PORT = .*/SSH_PORT = $GITEA_SSH_PORT/" "$CONFIG_FILE"
        fi
    fi

    if [ -n "$GITEA_ROOT_URL" ]; then
        sed -i "s|^ROOT_URL\s*=.*|ROOT_URL = ${GITEA_ROOT_URL}|" "$CONFIG_FILE"
    fi
fi

exec /usr/bin/gitea web --config /data/gitea/conf/app.ini
